version: "3.8"

services:
  database:
    image: mongo:4.0.28-xenial
    ports:
      - "27017:27017"
    volumes:
      - yolo:/data/db
    networks:
      - yolo-net

  backend:
    depends_on:
      - database
    build:
      context: ./backend
    image: yolo-backend:v1.0.0
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://database:27017/yolomy
    networks:
      - yolo-net

  frontend:
    depends_on:
      - backend
    build:
      context: ./client
    image: yolo-frontend:v1.0.0
    ports:
      - "3000:80"
    environment:
      REACT_APP_BACKEND_URL: http://backend:5000
    networks:
      - yolo-net

volumes:
  yolo:

networks:
  yolo-net:
    driver: bridge
