- name: Start yolo backend container
  community.docker.docker_container:
    name: yolo-backend
    image: birisi/yolo-backend:v1.0.0
    ports:
      - "5000:5000"
    env:
      MONGO_URI: mongodb://database:27017/yolomy
    networks:
      - name: yolo-net

  tags:
    - backend-start
