# ---
# - name: Run MongoDB Container
#   docker_container:
#     name: app-mongo
#     image: mongo
#     ports:
#       - '27017:27017'
#     volumes:
#       - ./app-mongo-data:/data/db
#     networks:
#       - name: app-net
#   tags:
#     - database
#     - backend

---
- name: Check app-net network
  community.docker.docker_network:
    name: app-net
    state: present

- name: Run MongoDB Container
  community.docker.docker_container:
    name: app-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./app-mongo-data:/data/db
    networks:
      - name: app-net
  tags:
    - database
    - backend
