- name: Run MongoDB container
  community.docker.docker_container:
    name: yolo-db
    image: "{{ database_image }}"
    ports:
      - "{{ database_port }}:27017"
    volumes:
      - yolo:/data/db
    networks:
      - name: yolo-net

  tags:
    - db-start
